# This workflow will check for Maven projects if the licenses of all (transitive) dependencies are vetted.

name: License vetting status check

on:
  pull_request:
    branches: 
      - 'master'
  issue_comment:
    types: [created]

jobs:
  check-licenses:
    if: github.event_name == 'pull_request' || (github.event.issue.pull_request != '' && startsWith(github.event.comment.body, '/request-license-review'))
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'

    - run: mvn clean generate-sources -f m2e-maven-runtime/pom.xml -B -Dtycho.mode=maven -Pgenerate-osgi-metadata

    - run: echo "request-review=true" >> $GITHUB_ENV
      if: github.event.issue.pull_request != '' && startsWith(github.event.comment.body, '/request-license-review')

    - name: License check
      run: |
        if [ ${{ env.request-review }} = true ]; then
          mvn -U -B -ntp org.eclipse.dash:license-tool-plugin:license-check -Ddash.fail=true -Ddash.iplab.token=${{ secrets.M2E_GITLAB_API_TOKEN }} -Ddash.projectId=technology.m2e
        else
          mvn -U -B -ntp org.eclipse.dash:license-tool-plugin:license-check -Ddash.fail=true
        fi
